// <auto-generated />
namespace QuanLyKhachSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class EditServiceAndRever : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditServiceAndRever));
        
        string IMigrationMetadata.Id
        {
            get { return "202006261122070_EditServiceAndRever"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
