// <auto-generated />
namespace QuanLyKhachSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddStatusPropati06072020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStatusPropati06072020));
        
        string IMigrationMetadata.Id
        {
            get { return "202007060747316_AddStatusPropati06072020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
